# ================================+++++++++====================
#                 _                          __ _       
#     /\/\   __ _(_)_ __     ___ ___  _ __  / _(_) __ _ 
#    /    \ / _` | | '_ \   / __/ _ \| '_ \| |_| |/ _` |
#   / /\/\ \ (_| | | | | | | (_| (_) | | | |  _| | (_| |
#   \/    \/\__,_|_|_| |_|  \___\___/|_| |_|_| |_|\__, |
#                                                 |___/ 
# ================================+++++++++====================

# sub config load
source=./autostart.conf
source=./env.conf
source=./animation.conf
source=./layout.conf
source=./effect.conf
source=./bind.conf
source=./rule.conf
source=./settings.conf
source=~/hakuspace-control/mango-custom.conf