# =======================================
#      __       _           
#     /__\_   _| | ___  ___ 
#    / \// | | | |/ _ \/ __|
#   / _  \ |_| | |  __/\__ \
#   \/ \_/\__,_|_|\___||___/
#
# =======================================         

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# Animation for layers
layerrule=animation_type_open:slide,layer_name:swaync-control-center
layerrule=animation_type_close:slide,layer_name:swaync-control-center
layerrule=noshadow:1,layer_name:swaync-control-center

layerrule=animation_type_open:slide,layer_name:rofi
layerrule=animation_type_close:slide,layer_name:rofi

# Scroller layout: Default proportion
windowrule=scroller_proportion:1.0,appid:zen
windowrule=scroller_proportion:1.0,appid:code
windowrule=scroller_proportion:0.65,appid:thunar

# Rules for hakuspace
windowrule=scroller_proportion:0.6,appid:seycmd
windowrule=scroller_proportion:0.4,appid:seyclock
windowrule=scroller_proportion:0.4,appid:seylavat
windowrule=scroller_proportion:0.4,appid:seycava

# Floating windows
windowrule=isfloating:1,title:Confirm to replace files*
windowrule=isfloating:1,title:File Operation Progress*

# Dockbar rules
layerrule=animation_type_open:slide,layer_name:dock*
layerrule=animation_type_close:slide,layer_name:dock*
layerrule=noshadow:1,layer_name:dock*

# Desktop icons rules
windowrule=isfloating:1,appid:desktop_icons.py,title:Rename
windowrule=width:300,height:100,appid:desktop_icons.py,title:Rename