general {
    lock_cmd = pidof hyprlock || ~/.local/bin/lock.sh
    before_sleep_cmd = loginctl lock-session && ~/.local/bin/dpms_handler.sh off
    after_sleep_cmd = ~/.local/bin/dpms_handler.sh on
}

# Set brightness
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
    condition_cmd = ~/.local/bin/check_audio.sh
    condition_retry = 10
}

# Lock screen
listener {
    timeout = 180
    on-timeout = loginctl lock-session
    condition_cmd = ~/.local/bin/check_audio.sh
    condition_retry = 10
}

# Turn off display (DPMS)
listener {
    timeout = 210
    on-timeout = ~/.local/bin/dpms_handler.sh off
    on-resume = ~/.local/bin/dpms_handler.sh on && sleep 0.5 && brightnessctl -r
    condition_cmd = ~/.local/bin/check_audio.sh
    condition_retry = 10
}

# Put machine to Sleep
listener {
    timeout = 420
    on-timeout = systemctl suspend
    condition_cmd = ~/.local/bin/check_audio.sh
    condition_retry = 30
}